### PR TITLE
Fix compiler warnings exposed by extra flags

### PR DESCRIPTION
**Pull request by rotty**
Note that this change makes use of the `AX_APPEND_COMPILE_FLAGS` macro
from the "Autoconf Archive"[1]; the list of warnings is taken from the
`AX_COMPILER_FLAGS_CFLAGS` macro. I've not directly used the latter
macro, as it enables dubious warnings such as
`-Wdeclaration-after-statement`.

Besides some minor tweaks to silence the warnings, the code changes in
this commit also fixes one definitive bug uncovered by the warnings,
namely the use of `size_t` instead of `ssize_t` when calling
`mq_receive`.

[1]: https://www.gnu.org/software/autoconf-archive/

----

Note that this change has room for improvement (IMO):

- It introduces a build dependency on `autoconf-archive`, when
  building from git (not when building from a release tarball). This
  could be fixed by including the code for `AX_APPEND_COMPILE_FLAGS`
  in the repo, probably after cleaning it up and simplifying it a
  bit. I could do that, if it's deemed desirable.

- The list of warnings should be considered more carefully, but this
  should be a reasonable starting point.

### CODE REVIEW

**Comment by goeb** [comment]
Thank you for your contribution.

However I have 2 remarks.

1. Your patch raises an autoconf error on my computer:
```
configure.ac:14: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

It would be simpler to add something like:

```
mq_CFLAGS = \
    -Wall \
    -Wextra \
    -Wundef \
    ...
```

2. I accept the part of your patch that modifies src/mq.c. Could you please split your commit in 2 commits: one for the src/mq.c, that I will accept, and one for the autotools part, that is still being discussed?
(In fact I do not know if I will be able to merge only 1 commit out of 2 of a pull request)

**Comment by rotty** [comment]
> Thank you for your contribution.
> 
> However I have 2 remarks.
> 
>  1. Your patch raises an autoconf error on my computer:
> 
> 
> ```
> configure.ac:14: error: possibly undefined macro: dnl
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /usr/bin/autoconf failed with exit status: 1
> ```
> 
Interesting; I just checked that the code I pushed (commit dce85a86f7cb9) does not cause that error on my machine (autoconf 2.69, automake 1.16.1, m4 1.4.18), and `autoreconf -i` works fine here, albeit I seem to recall encountering this error during development of the patch. What autotool versions do you use? Anyway, this issue is expected to go away in the split-out, cleaned-up version of the buildsystem changes (see below).

> It would be simpler to add something like:
> 
> ```
> mq_CFLAGS = \
>     -Wall \
>     -Wextra \
>     -Wundef \
>     ...
> ```
> 
It would, but the idea of using the `AX_*` machinery is that it checks for available compiler flags, and only enables flags that are actually supported by the chosen toolchain, so this works for different toolchains (e.g., GCC and clang), as well as for different versions of, say, GCC. You should always get the maximum subset of warning flags supported by the toolchain.

>  1. I accept the part of your patch that modifies src/mq.c. Could you please split your commit in 2 commits: one for the src/mq.c, that I will accept, and one for the autotools part, that is still being discussed?
>
I'll split off the build system changes into their own PR, so they can be considered separately.

>  (In fact I do not know if I will be able to merge only 1 commit out of 2 of a pull request)
>
You could do that easily on the git level, but cherry-picking commits doesn't map well (or at all) to the Github model of pull requests, as far as I'm aware.

*[ BTW, as a somewhat-related note, you could make use of the `rebase` option for merging PRs to obtain a simpler resulting git history, but people have different preferences here, just thought I'd mention it ].*

**Comment by rotty** [comment]
>     1. Your patch raises an autoconf error on my computer:
> 
Do you have `autoconf-archive` installed? This could be the source of the error (autoconf errors are notoriously unhelpful).

**Comment by rotty** [comment]
@goeb I've now updated this PR to only contain the code changes. I'll submit another PR with the build system changes when I've come around to polish the changes, including not requiring the `autoconf-archive` build dependency.

**Comment by goeb** [comment]
I have manually merged your commit on src/mq.c.

> Do you have autoconf-archive installed?

No. After installing autoconf-archive, the error disappeared.

**Pull request merged**
